src/Entity/Adherent.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use App\Bundles\Validator\AdherentConstraint;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdherentRepository")
 * @UniqueEntity(
 *     fields = {"Username"},
 *     message = "Le nom d'adhérent est déjà utilisé"
 * )
 * @AdherentConstraint()
 */
class Adherent implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Regex(
     *     pattern="/^[a-zA-Z0-9_]*$/",
     *     message="Votre identifiant ne doit comporter que des minuscules, majuscules, chiffres et '_' sans caractères spéciaux"
     * )
     * @Assert\Length(
     *     min=8,
     *     max=20,
     *     minMessage="Votre identifiant doit comporter au moins 8 caractères",
     *     maxMessage="Votre identifiant doit comporter au plus 20 caractères"
     * )
     */
    private $Username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Prenom;

    /**
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email(
     *     message = "'{{ value }}' n'est pas une adresse mail valide.",
     *     checkMX = true
     * )
     */
    private $Mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CodeSecret;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(
     *     min="8",
     *     minMessage="Votre mot de passe doit comporter au minimum 8 caractères"
     * )
     */
    private $Password;

    /**
     * @Assert\NotBlank()
     * @Assert\EqualTo(propertyPath="Password", message="Password et confirm_password sont différents")
     */
    public $confirm_Password;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=32)
     */
    private $Genre;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    public $inscrType;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Adresse1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Adresse2;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $CodePostal;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Profession;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateNaissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $LieuNaissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $DepartementNaissance;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $TelFix;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $TelPort;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Diplome", mappedBy="user")
     */
    private $diplomes;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fEtudiant;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $NiveauSca;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $NiveauApn;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fApneeSca;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $Activite;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fBenevole;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fEncadrant;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $AccidentNom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $AccidentPrenom;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $AccidentTelFix;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $AccidentTelPort;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $DateCertif;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fAllergAspirine;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $Licence;

    private $fLicence;
    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $Cotisation;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fCarteGUC;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fCarteSIUAPS;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fMailGUC;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fTrombi;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $EnvoiGUC;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $EnvoiSIUAPS;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Facture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $RefFacture;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $Assurance;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $PretMateriel;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $PretMaterielOld;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $MineurNom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $MineurPrenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $MineurQualite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ModifUser;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $DateModifUser;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $DatePremInscr;

    /**
     * @ORM\Column(type="text", length=512, nullable=true)
     */
    private $AdminOK;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Comments;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $ReducFamilleID;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $ReducFam;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Role", mappedBy="adherent", cascade="persist")
     */
    private $roles;

    private $reglementRGPD;
    private $mineurSign;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MatCal", mappedBy="RefUser")
     */
    private $matCals;


    public function __construct()
    {
        $this->roles = new ArrayCollection();
        $this->matCals = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * @param mixed $Username
     */
    public function setUsername($Username): void
    {
        $this->Username = $Username;
    }

    public function getUsername()
    {
        return $this->Username;
    }

    public function getGenre(): ?string
    {
        return $this->Genre;
    }

    public function setGenre(?string $Genre): self
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getAdresse1(): ?string
    {
        return $this->Adresse1;
    }

    public function setAdresse1(?string $Adresse1): self
    {
        $this->Adresse1 = $Adresse1;

        return $this;
    }

    public function getAdresse2(): ?string
    {
        return $this->Adresse2;
    }

    public function setAdresse2(?string $Adresse2): self
    {
        $this->Adresse2 = $Adresse2;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->CodePostal;
    }

    public function setCodePostal(?string $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(?string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

src/Controller/Intranet/Admin/IndexAdminController.php
<?php

namespace App\Controller\Intranet\Admin;

use App\Classes\Form\FormConst;
use App\Entity\User;
use App\Entity\FilterDroits;
use App\Entity\Role;
use App\Form\FilterDroitsType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IndexAdminController extends AbstractController
{
    /**
     * @Route("/intranet/admin_export_trombi", name="admin_export_trombi")
     */
    public function adminExportTrombi()
    {
        return $this->render('');
    }

    private function encodeResponse($response)
    {
        return new Response(json_encode($response));
    }

    /**
     * @Route("/intranet/admin/ajax_droits", name="ajax_droits")
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return Response
     */
    public function ajaxDroits(EntityManagerInterface $em, Request $request) : Response
    {
        $id = $request->get('id');
        $value = $request->get('value');

        $v = explode('-', $id);

        if (count($v) < 3 || $v[0] != 'ck') {
            return $this->encodeResponse([]);
        }

        $userId = $v[1];
        $role   = $v[2];

        if (!is_numeric($userId)) {
            return $this->encodeResponse([]);
        }
        // Recherche du droit concerné dans la base

        /** @var UserRepository $adh */
        $adh = $em->getRepository(User::class);
        $user = $adh->find($userId);


        switch ($value) {
            case 'true':
                foreach ($user->getRolesAsObjects() as $v) {
                    if ($v->getRole() == $role) {
                        // Le role existe déjà
                        return $this->encodeResponse([]);
                    }
                }
                $r = (new Role())->setRole($role);
                $user->addRole($r);
                $em->persist($r);
                break;
            case 'false':
                foreach ($user->getRolesAsObjects() as $v) {
                    if ($v->getRole() == $role) {
                        $user->removeRole($v);
                        $em->remove($v);
                    }
                }
                break;
        }
        //$em->persist($user);
        $em->flush();

        return $this->encodeResponse([
            'id' => $id,
            'newState' => $value
        ]);
    }

    /**
     * @Route("/intranet/admin/admin_droits_utilisateur", name="admin_droits")
     * @param EntityManagerInterface $em
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function adminDroits(EntityManagerInterface $em, PaginatorInterface $paginator, Request $request)
    {
        $search = new FilterDroits();
        $form = $this->createForm(FilterDroitsType::class, $search);
        $form->handleRequest($request);

        /** @var UserRepository $ar */
        $ar = $em->getRepository(User::class);
        $query = $ar->getUserssRights($search);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            15 /*limit per page*/
        );
        return $this->render('intranet/admin/admin_droits.html.twig', [
            'pagination' => $pagination,
            'roles' => FormConst::LISTE_ROLES,
            'abbr_roles' => FormConst::ABBREV_ROLES,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/intranet/admin_gen_excel/full", name="admin_gen_excel_full")
     */
    public function adminGenExcelFull()
    {
        return $this->render('');
    }

    /**
     * @Route("/intranet/admin_gen_excel/inscrits", name="admin_gen_excel_inscrits")
     */
    public function adminGenExcelInscrits()
    {
        return $this->render('');
    }

    /**
     * @Route("/intranet/admin_info_server/php", name="admin_info_server_php")
     */
    public function adminInfoPHP()
    {
        return $this->render('');
    }

    /**
     * @Route("/intranet/admin_info_server/mysql", name="admin_info_server_mysql")
     */
    public function adminInfoMySQL()
    {
        return $this->render('');
    }

    /**
     * @Route("/intranet/admin_log/mysql", name="admin_log_mysql")
     */
    public function adminLogMysql()
    {
        return $this->render('');
    }

    /**
     * @Route("/intranet/admin_log/reset_log_mysql", name="admin_reset_log_mysql")
     */
    public function adminResetLogMysql()
    {
        return $this->render('');
    }

    /**
     * @Route("/intranet/admin_log/mail", name="admin_log_mail")
     */
    public function adminLogMail()
    {
        return $this->render('');
    }

    /**
     * @Route("/intranet/admin_log/intranet", name="admin_log_intranet")
     */
    public function adminResetLogMyssql()
    {
        return $this->render('');
    }
}

src/Controller/Intranet/IndexBaptemeController.php
<?php

namespace App\Controller\Intranet;

use App\Entity\User;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class IndexBaptemeController extends AbstractController
{
    /**
     * @Route("/intranet/bapteme", name="xx_index_bapteme")
     * @param RegistryInterface $doctrine
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(RegistryInterface $doctrine)
    {
        $user = $this->getUser();
        $adh = $doctrine->getRepository(User::class)->find($user->getId());
        return $this->render('intranet/index.html.twig', [
            'adh' => $adh
        ]);
    }
}

src/Controller/Intranet/IndexGonflageController.php
<?php

namespace App\Controller\Intranet;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class IndexGonflageController extends AbstractController
{
    /**
     * @Route("/gonflage/modif_eleves", name="index_modif_gonf_eleves")
     */
    public function indexModifGonfEleves()
    {
        return $this->render('');
    }

    /**
     * @Route("/gonflage/index_status_gonflage_eleves", name="index_status_gonflage_eleves")
     */
    public function indexStatusGonflageEleves()
    {
        return $this->render('');
    }
}

src/Controller/Intranet/Inscription/Admin/IndexInscriptionAdminController.php
<?php


namespace App\Controller\Intranet\Inscription\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;


class IndexInscriptionAdminController extends AbstractController
{

    /**
     * @Route("/intranet/index_admin_status_inscriptions", name="index_admin_status_inscriptions")
     */
    public function adminStatusInscription()
    {
        return $this->render('');
    }


}

src/Controller/Intranet/Inscription/IndexInscriptionAdminController.php
<?php


namespace App\Controller\Intranet\Inscription;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;


class IndexInscriptionAdminController extends AbstractController
{

    /**
     * @Route("/intranet/index_admin_status_inscriptions", name="index_admin_status_inscriptions")
     */
    public function adminStatusInscription()
    {
        return $this->render('');
    }


}

templates/intranet/gonflage/_aff_calendrier.html.twig
<div class="col-xs-12">
    <div class="table-responsive">
        <table class="table table-bordered table-hover calendrier_eleves">
            <tr>
                <th>Date</th>
                <th>Aide 1</th>
                <th>Aide 2</th>
                <th>Aide 3</th>
                <th>Responsable séance</th>
            </tr>

            {% if msgErreur != '' %}
                <tr><td colspan='5'><h2 class="red">{{ msgErreur }}</h2></td></tr>
            {% endif %}

            {% for cal in calendrier %}
                <tr>
                    {% if cal.seanceGonflage == 'O' %}
                        <td>{{ cal.date | date('d/m/Y') }}</td>
                        <form method="post" action="{{ url('ajax_calendrier') }}">

                            {# Cas a gérer :
                             1 - aide == '' et qqsoit aidevalide   -> le créneau est vide, on affiche une checkbox
                             pour pouvoir prendre le créneau
                             2 - aide != '' et aide != currentuser -> le créneau est pris
                             3 - aide != '' et aide == currentuser -> le créneau est pris par l'utilisateur, mais on
                             affiche la checkbox.
                             ----------------------------------------------------------------------------------------
                             #}
                            {% set nomComplet = app.user.nom ~ ' ' ~ app.user.prenom %}

                            {% include 'intranet/gonflage/_case.html.twig' with {
                                id: cal.id,
                                aideGonf: cal.aideGonf1 ,
                                aideValidee: cal.aide1Validee,
                                aideNumber: 'aide1',
                                nomComplet: nomComplet
                            }%}

                            {% include 'intranet/gonflage/_case.html.twig' with {
                                id: cal.id,
                                aideGonf: cal.aideGonf2 ,
                                aideValidee: cal.aide2Validee,
                                aideNumber: 'aide2',
                                nomComplet: nomComplet
                            }%}

                            {% include 'intranet/gonflage/_case.html.twig' with {
                                id: cal.id,
                                aideGonf: cal.aideGonf3 ,
                                aideValidee: cal.aide3Validee,
                                aideNumber: 'aide3',
                                nomComplet: nomComplet
                            }%}

                            <td class="center">{{ cal.respGonflage }}</td>
                        </form>
                    {% else %}
                        <td>{{ cal.date | date('d/m/Y') }}</td>
                        <td class="center grey2" colspan="4">Piscine fermée</td>
                    {% endif %}
                </tr>
            {% endfor %}

        </table>
    </div>
</div>

templates/intranet/gonflage/_aff_planning.html.twig
{% if seancesUser | length > 0 %}
    <div class="col-xs-12">
        <h3>Planning d'aide au gonflage</h3>
        <p>Récapitulatif des séances vous concernant :</p>
    </div>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">

        {% for seanceUser in seancesUser %}
            {% set date = seanceUser.date | date('d/m/Y') %}
            {% if seanceUser.aideGonf1 == user %}
                {% set v = seanceUser.Aide1Validee %}
            {% elseif seanceUser.aideGonf2 == user %}
                {% set v = seanceUser.Aide2Validee %}
            {% elseif seanceUser.aideGonf3 == user %}
                {% set v = seanceUser.Aide3Validee %}
            {% else %}
                {% set v = 'X' %}
            {% endif %}

            {% set st = '' %}

            {% if v == '' or v == 'NA' %}
                {% set st = 'Inscrit' %}
                {% set col = 'badge-primary' %}
            {% elseif v == 'O' %}
                {% set st = 'Validée' %}
                {% set col = 'badge-success' %}
            {% elseif v == 'N' %}
                {% set st = 'Absent' %}
                {% set col = 'badge-danger' %}
            {% endif %}
            <div class="col mb-4">
                <div class="card">
                    <div class="card-body">
                        <strong class="mr-auto">{{ date }} </strong><div class="badge {{ col }}">{{ st }}</div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{#
         <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <tr>
                    <th>Date</th>
                    <th>Status</th>
                </tr>

                {% for seanceUser in seancesUser %}

                    {% set date = seanceUser.date | date('d/m/Y') %}

                    {% if seanceUser.aideGonf1 == user %}
                        {% set v = seanceUser.Aide1Validee %}
                    {% elseif seanceUser.aideGonf2 == user %}
                        {% set v = seanceUser.Aide2Validee %}
                    {% elseif seanceUser.aideGonf3 == user %}
                        {% set v = seanceUser.Aide3Validee %}
                    {% else %}
                        {% set v = 'X' %}
                    {% endif %}

                    {% set st = '' %}

                    {% if v == '' or v == 'NA' %}
                        {% set st = 'Inscrit' %}
                    {% elseif v == 'O' %}
                        {% set st = 'Validée' %}
                    {% elseif v == 'N' %}
                        {% set st = 'Absent' %}
                    {% endif %}

                    <tr><td>{{ date }}</td><td>{{ st }}</td></tr>
                {% endfor %}

            </table>
        </div>
    </div>
    #}
{% endif %}

templates/intranet/gonflage/_aff_synthese.html.twig
{% if seancesValidees < conf('nb_sess_req') and
    ACTIVITE == 'Prépa N2' or ACTIVITE == 'Prépa N3' or ACTIVITE == 'Prépa N4' %}

    <p>Sur cette page, vous pouvez choisir les créneaux ou vous souhaitez participer. N'oubliez pas que
        vous devez participer à {{ conf(nb_sess_req) }} séances pour valider votre niveau. Les
        séances sont validées si vous êtes présents. En cas d'impossibilité de venir, il vous incombera
        de trouver un remplaçant; en effet, sans aide suffisante, le gonflage et la désinfection ne peuvent être réalisés
        dans de bonnes conditions, et la séance piscine devra donc se faire sans bloc ni détendeur.
        A cet instant votre participation est la suivante:</p>
    <ul>
        <li>Vous vous êtes inscrit à {{ nbSeances }} séance{% if nbSeances > 1 %}s{% endif %}</li>
        <li>
            {% if nbValidees == 0 %}
                Aucune séance validée
            {% else %}
                {% if nbValidees > 1 %}
                    {{ nbValidees }} séances ont été validées
                {% else %}
                    1 séance a été validée
                {% endif %}
            {% endif %}
        </li>

        {% if nbNonvalidees > 1 %}
            <li class="red">Vous avez manqué {{ nbNonvalidees }} séances</li>
        {% else %}
            {% if nbNonvalidees == 1 %}
                <li class="red">Vous avez manqué 1 séance</li>
            {% else %}
                <li>Vous n'avez manqué aucune séance</li>
            {% endif %}
        {% endif %}
    </ul>
{% else %}
    <p>Sur cette page, vous pouvez choisir les créneaux ou vous souhaitez participer.</p>
    <p>Vous avez atteint le nombre de participations requis pour valider votre niveau, ou l'activité que vous
        avez choisi cette année ne vous demande pas la participation à ces séances. Vous pouvez tout de même
        vous inscrire afin de participer à la vie du club</p>

{% endif %}

templates/intranet/gonflage/_case.html.twig
{#
id: cal.id,
aideGonf: cal.aideGonf1 ,
aideValidee: cal.aide1Validee,
aideNumber: 'aide1',
nomComplet: nomComplet
#}

{% if aideGonf == '' %}
    <td class="tbcolor center">
        <input type="checkbox" class="ajax-select" name="{{ aideNumber }}" id="ck-{{ id }}-{{ aideNumber }}">
        <span class="nameCal"></span>
    </td>
{% else %}
    {% if aideGonf == nomComplet %}
        {% if aideValidee == 'NA' or aideValidee == '' %}
            <td class="tbcolor table-success center">
                <input type="checkbox" class="ajax-select" name="{{ aideNumber }}" id="ck-{{ id }}-{{ aideNumber }}" checked>
                <span class="nameCal">{{ nomComplet }}</span>
            </td>
        {% endif %}
    {% else %}
        <td class="table-danger center">{{ aideGonf }}</td>
    {% endif %}
{% endif %}

templates/intranet/gonflage/modif_eleve.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modif du calendrier de gonflage{% endblock %}

{% block main_page %}

    {% import 'macros/bouton.html.twig' as control %}

    <div class="container">

        <div class="col-xs-12 gonflage_planning">
            {% include "intranet/gonflage/_aff_planning.html.twig" %}
        </div>

        <div class="col-xs-12">
            <h3>Modification/Consultation du planning de gonflage pour {{ app.user.Nom ~ ' ' ~ app.user.prenom }}</h3>
        </div>

        <div class="alert alert-danger gonflage_error sticky-top" role="alert" hidden></div>

        <div class="col-xs-12 gonflage_synthese">
            {% include "intranet/gonflage/_aff_synthese.html.twig" %}
        </div>

        <div class="calendrier_eleves">
            {% include 'intranet/gonflage/_aff_calendrier.html.twig' %}
        </div>

        <div class="col-xs-12">
            <a class="btn btn-light btn-outline-guc btn-block" href="{{ url('index_intranet') }}">
                <span class="glyphicon glyphicon-chevron-left"></span> Revenir à l'accueil de l'intranet.</a>
        </div>

    </div>

{% endblock %}

{% block javascripts_end %}

    {{ parent() }}
    {{ encore_entry_script_tags('gonflage') }}

{% endblock %}